### ISSUE TITLE
Do Now 5.01 NameError: name 'init' is not defined

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#68]
I tried running the Intro_Script from the Do Now 5.01 unit and got the following ingraious output:

Traceback (most recent call last):  
  File "/home/ubuntu/workspace/python/earsketch.py", line 1, in <module>  
    from earsketch import \*  
  File "/home/ubuntu/workspace/python/earsketch.py", line 2, in <module>  
    init()  
NameError: name 'init' is not defined    

It looks like it picked up the import statement, but did not find the init() function.
I guess I am just another dead "beat"  in the water.

**Comment by TEALS-IntroCS** [comment]
I can't reproduce the issue. Can you add a screenshot of your Earsketch workspace with the issue?
